// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: kyc_kyb.proto

package config

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusInfo int32

const (
	// Process is pending
	StatusInfo_Pending StatusInfo = 0
	// in-process
	StatusInfo_InProcess StatusInfo = 1
	// Process has failed
	StatusInfo_Failed StatusInfo = 2
	// Process is Partially complete
	StatusInfo_Partial StatusInfo = 3
	// Process is done
	StatusInfo_Done StatusInfo = 4
	// ReVerification is needed
	StatusInfo_ReVerificationNeeded StatusInfo = 5
)

// Enum value maps for StatusInfo.
var (
	StatusInfo_name = map[int32]string{
		0: "Pending",
		1: "InProcess",
		2: "Failed",
		3: "Partial",
		4: "Done",
		5: "ReVerificationNeeded",
	}
	StatusInfo_value = map[string]int32{
		"Pending":              0,
		"InProcess":            1,
		"Failed":               2,
		"Partial":              3,
		"Done":                 4,
		"ReVerificationNeeded": 5,
	}
)

func (x StatusInfo) Enum() *StatusInfo {
	p := new(StatusInfo)
	*p = x
	return p
}

func (x StatusInfo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusInfo) Descriptor() protoreflect.EnumDescriptor {
	return file_kyc_kyb_proto_enumTypes[0].Descriptor()
}

func (StatusInfo) Type() protoreflect.EnumType {
	return &file_kyc_kyb_proto_enumTypes[0]
}

func (x StatusInfo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusInfo.Descriptor instead.
func (StatusInfo) EnumDescriptor() ([]byte, []int) {
	return file_kyc_kyb_proto_rawDescGZIP(), []int{0}
}

type TenantUserLevelKycGetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org name for kyc req
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUserLevelKycGetReq) Reset() {
	*x = TenantUserLevelKycGetReq{}
	mi := &file_kyc_kyb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserLevelKycGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserLevelKycGetReq) ProtoMessage() {}

func (x *TenantUserLevelKycGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserLevelKycGetReq.ProtoReflect.Descriptor instead.
func (*TenantUserLevelKycGetReq) Descriptor() ([]byte, []int) {
	return file_kyc_kyb_proto_rawDescGZIP(), []int{0}
}

func (x *TenantUserLevelKycGetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TenantLevelKCGetReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// org name for kyb req
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantLevelKCGetReq) Reset() {
	*x = TenantLevelKCGetReq{}
	mi := &file_kyc_kyb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantLevelKCGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantLevelKCGetReq) ProtoMessage() {}

func (x *TenantLevelKCGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantLevelKCGetReq.ProtoReflect.Descriptor instead.
func (*TenantLevelKCGetReq) Descriptor() ([]byte, []int) {
	return file_kyc_kyb_proto_rawDescGZIP(), []int{1}
}

func (x *TenantLevelKCGetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TenantUserLevelKycResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantUserLevelKyc Status for tenant
	TenantUserLevelKycStatus StatusInfo `protobuf:"varint,1,opt,name=TenantUserLevelKycStatus,proto3,enum=config.StatusInfo" json:"TenantUserLevelKycStatus,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TenantUserLevelKycResp) Reset() {
	*x = TenantUserLevelKycResp{}
	mi := &file_kyc_kyb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUserLevelKycResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUserLevelKycResp) ProtoMessage() {}

func (x *TenantUserLevelKycResp) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUserLevelKycResp.ProtoReflect.Descriptor instead.
func (*TenantUserLevelKycResp) Descriptor() ([]byte, []int) {
	return file_kyc_kyb_proto_rawDescGZIP(), []int{2}
}

func (x *TenantUserLevelKycResp) GetTenantUserLevelKycStatus() StatusInfo {
	if x != nil {
		return x.TenantUserLevelKycStatus
	}
	return StatusInfo_Pending
}

type TenantLevelKCResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantLevelKC Status for tenant
	TenantLevelKCStatus StatusInfo `protobuf:"varint,1,opt,name=TenantLevelKCStatus,proto3,enum=config.StatusInfo" json:"TenantLevelKCStatus,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TenantLevelKCResp) Reset() {
	*x = TenantLevelKCResp{}
	mi := &file_kyc_kyb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantLevelKCResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantLevelKCResp) ProtoMessage() {}

func (x *TenantLevelKCResp) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_kyb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantLevelKCResp.ProtoReflect.Descriptor instead.
func (*TenantLevelKCResp) Descriptor() ([]byte, []int) {
	return file_kyc_kyb_proto_rawDescGZIP(), []int{3}
}

func (x *TenantLevelKCResp) GetTenantLevelKCStatus() StatusInfo {
	if x != nil {
		return x.TenantLevelKCStatus
	}
	return StatusInfo_Pending
}

var File_kyc_kyb_proto protoreflect.FileDescriptor

const file_kyc_kyb_proto_rawDesc = "" +
	"\n" +
	"\rkyc_kyb.proto\x12\x06config\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\".\n" +
	"\x18TenantUserLevelKycGetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\x13TenantLevelKCGetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"h\n" +
	"\x16TenantUserLevelKycResp\x12N\n" +
	"\x18TenantUserLevelKycStatus\x18\x01 \x01(\x0e2\x12.config.StatusInfoR\x18TenantUserLevelKycStatus\"Y\n" +
	"\x11TenantLevelKCResp\x12D\n" +
	"\x13TenantLevelKCStatus\x18\x01 \x01(\x0e2\x12.config.StatusInfoR\x13TenantLevelKCStatus*e\n" +
	"\n" +
	"StatusInfo\x12\v\n" +
	"\aPending\x10\x00\x12\r\n" +
	"\tInProcess\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02\x12\v\n" +
	"\aPartial\x10\x03\x12\b\n" +
	"\x04Done\x10\x04\x12\x18\n" +
	"\x14ReVerificationNeeded\x10\x052\xa8\x02\n" +
	"\x10TenantManagement\x12\x8e\x01\n" +
	"\x1bGetTenantUserLevelKycStatus\x12 .config.TenantUserLevelKycGetReq\x1a\x1e.config.TenantUserLevelKycResp\"-\x82\xd3\xe4\x93\x02'\x12%/v1/api/tenant-mgmt/tenant/{name}/kyc\x12\x82\x01\n" +
	"\x16GetTenantLevelKCStatus\x12\x1b.config.TenantLevelKCGetReq\x1a\x19.config.TenantLevelKCResp\"0\x82\xd3\xe4\x93\x02*\x12(/v1/api/tenant-mgmt/v1/tenant/{name}/kybBu\x92A?\x12\x1c\n" +
	"\x15TenantManagement API 2\x031.0r\x1f\n" +
	"\x1dTenantManagement API, KYC_KYBZ1github.com/coredgeio/tenant-management/api/configb\x06proto3"

var (
	file_kyc_kyb_proto_rawDescOnce sync.Once
	file_kyc_kyb_proto_rawDescData []byte
)

func file_kyc_kyb_proto_rawDescGZIP() []byte {
	file_kyc_kyb_proto_rawDescOnce.Do(func() {
		file_kyc_kyb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_kyb_proto_rawDesc), len(file_kyc_kyb_proto_rawDesc)))
	})
	return file_kyc_kyb_proto_rawDescData
}

var file_kyc_kyb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kyc_kyb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kyc_kyb_proto_goTypes = []any{
	(StatusInfo)(0),                  // 0: config.StatusInfo
	(*TenantUserLevelKycGetReq)(nil), // 1: config.TenantUserLevelKycGetReq
	(*TenantLevelKCGetReq)(nil),      // 2: config.TenantLevelKCGetReq
	(*TenantUserLevelKycResp)(nil),   // 3: config.TenantUserLevelKycResp
	(*TenantLevelKCResp)(nil),        // 4: config.TenantLevelKCResp
}
var file_kyc_kyb_proto_depIdxs = []int32{
	0, // 0: config.TenantUserLevelKycResp.TenantUserLevelKycStatus:type_name -> config.StatusInfo
	0, // 1: config.TenantLevelKCResp.TenantLevelKCStatus:type_name -> config.StatusInfo
	1, // 2: config.TenantManagement.GetTenantUserLevelKycStatus:input_type -> config.TenantUserLevelKycGetReq
	2, // 3: config.TenantManagement.GetTenantLevelKCStatus:input_type -> config.TenantLevelKCGetReq
	3, // 4: config.TenantManagement.GetTenantUserLevelKycStatus:output_type -> config.TenantUserLevelKycResp
	4, // 5: config.TenantManagement.GetTenantLevelKCStatus:output_type -> config.TenantLevelKCResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kyc_kyb_proto_init() }
func file_kyc_kyb_proto_init() {
	if File_kyc_kyb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_kyb_proto_rawDesc), len(file_kyc_kyb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_kyb_proto_goTypes,
		DependencyIndexes: file_kyc_kyb_proto_depIdxs,
		EnumInfos:         file_kyc_kyb_proto_enumTypes,
		MessageInfos:      file_kyc_kyb_proto_msgTypes,
	}.Build()
	File_kyc_kyb_proto = out.File
	file_kyc_kyb_proto_goTypes = nil
	file_kyc_kyb_proto_depIdxs = nil
}
