// Copyright 2025, Coredge.io Inc.
// All Rights reserved.
//
// Author Akash Sharma (akash.sharma@coredge.io)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sample.proto

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SampleApi_HelloWorld_FullMethodName = "/config.SampleApi/HelloWorld"
)

// SampleApiClient is the client API for SampleApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleApiClient interface {
	// hello world
	HelloWorld(ctx context.Context, in *HelloWorldReq, opts ...grpc.CallOption) (*HelloWorldResp, error)
}

type sampleApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleApiClient(cc grpc.ClientConnInterface) SampleApiClient {
	return &sampleApiClient{cc}
}

func (c *sampleApiClient) HelloWorld(ctx context.Context, in *HelloWorldReq, opts ...grpc.CallOption) (*HelloWorldResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloWorldResp)
	err := c.cc.Invoke(ctx, SampleApi_HelloWorld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleApiServer is the server API for SampleApi service.
// All implementations must embed UnimplementedSampleApiServer
// for forward compatibility.
type SampleApiServer interface {
	// hello world
	HelloWorld(context.Context, *HelloWorldReq) (*HelloWorldResp, error)
	mustEmbedUnimplementedSampleApiServer()
}

// UnimplementedSampleApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSampleApiServer struct{}

func (UnimplementedSampleApiServer) HelloWorld(context.Context, *HelloWorldReq) (*HelloWorldResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedSampleApiServer) mustEmbedUnimplementedSampleApiServer() {}
func (UnimplementedSampleApiServer) testEmbeddedByValue()                   {}

// UnsafeSampleApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleApiServer will
// result in compilation errors.
type UnsafeSampleApiServer interface {
	mustEmbedUnimplementedSampleApiServer()
}

func RegisterSampleApiServer(s grpc.ServiceRegistrar, srv SampleApiServer) {
	// If the following call pancis, it indicates UnimplementedSampleApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SampleApi_ServiceDesc, srv)
}

func _SampleApi_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloWorldReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleApiServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SampleApi_HelloWorld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleApiServer).HelloWorld(ctx, req.(*HelloWorldReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleApi_ServiceDesc is the grpc.ServiceDesc for SampleApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.SampleApi",
	HandlerType: (*SampleApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _SampleApi_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sample.proto",
}
