// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TenantMgmtApiClient is the client API for TenantMgmtApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantMgmtApiClient interface {
	// get tenant level kyc status
	GetTenantLevelKycStatus(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*TenantLevelKycStatusResp, error)
	// get tenant user level kyc status
	GetTenantUserLevelKycStatus(ctx context.Context, in *TenantUserLevelKycStatusReq, opts ...grpc.CallOption) (*TenantUserLevelKycStatusResp, error)
	// get payment configuration status
	GetPaymentMethodConfigurationStatus(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*PaymentMethodConfigurationStatusResp, error)
	// get tenant type
	GetTenantType(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*TenantTypeResp, error)
}

type tenantMgmtApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantMgmtApiClient(cc grpc.ClientConnInterface) TenantMgmtApiClient {
	return &tenantMgmtApiClient{cc}
}

func (c *tenantMgmtApiClient) GetTenantLevelKycStatus(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*TenantLevelKycStatusResp, error) {
	out := new(TenantLevelKycStatusResp)
	err := c.cc.Invoke(ctx, "/config.TenantMgmtApi/GetTenantLevelKycStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMgmtApiClient) GetTenantUserLevelKycStatus(ctx context.Context, in *TenantUserLevelKycStatusReq, opts ...grpc.CallOption) (*TenantUserLevelKycStatusResp, error) {
	out := new(TenantUserLevelKycStatusResp)
	err := c.cc.Invoke(ctx, "/config.TenantMgmtApi/GetTenantUserLevelKycStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMgmtApiClient) GetPaymentMethodConfigurationStatus(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*PaymentMethodConfigurationStatusResp, error) {
	out := new(PaymentMethodConfigurationStatusResp)
	err := c.cc.Invoke(ctx, "/config.TenantMgmtApi/GetPaymentMethodConfigurationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantMgmtApiClient) GetTenantType(ctx context.Context, in *GenericStatusReq, opts ...grpc.CallOption) (*TenantTypeResp, error) {
	out := new(TenantTypeResp)
	err := c.cc.Invoke(ctx, "/config.TenantMgmtApi/GetTenantType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantMgmtApiServer is the server API for TenantMgmtApi service.
// All implementations must embed UnimplementedTenantMgmtApiServer
// for forward compatibility
type TenantMgmtApiServer interface {
	// get tenant level kyc status
	GetTenantLevelKycStatus(context.Context, *GenericStatusReq) (*TenantLevelKycStatusResp, error)
	// get tenant user level kyc status
	GetTenantUserLevelKycStatus(context.Context, *TenantUserLevelKycStatusReq) (*TenantUserLevelKycStatusResp, error)
	// get payment configuration status
	GetPaymentMethodConfigurationStatus(context.Context, *GenericStatusReq) (*PaymentMethodConfigurationStatusResp, error)
	// get tenant type
	GetTenantType(context.Context, *GenericStatusReq) (*TenantTypeResp, error)
	mustEmbedUnimplementedTenantMgmtApiServer()
}

// UnimplementedTenantMgmtApiServer must be embedded to have forward compatible implementations.
type UnimplementedTenantMgmtApiServer struct {
}

func (UnimplementedTenantMgmtApiServer) GetTenantLevelKycStatus(context.Context, *GenericStatusReq) (*TenantLevelKycStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantLevelKycStatus not implemented")
}
func (UnimplementedTenantMgmtApiServer) GetTenantUserLevelKycStatus(context.Context, *TenantUserLevelKycStatusReq) (*TenantUserLevelKycStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantUserLevelKycStatus not implemented")
}
func (UnimplementedTenantMgmtApiServer) GetPaymentMethodConfigurationStatus(context.Context, *GenericStatusReq) (*PaymentMethodConfigurationStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentMethodConfigurationStatus not implemented")
}
func (UnimplementedTenantMgmtApiServer) GetTenantType(context.Context, *GenericStatusReq) (*TenantTypeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantType not implemented")
}
func (UnimplementedTenantMgmtApiServer) mustEmbedUnimplementedTenantMgmtApiServer() {}

// UnsafeTenantMgmtApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantMgmtApiServer will
// result in compilation errors.
type UnsafeTenantMgmtApiServer interface {
	mustEmbedUnimplementedTenantMgmtApiServer()
}

func RegisterTenantMgmtApiServer(s grpc.ServiceRegistrar, srv TenantMgmtApiServer) {
	s.RegisterService(&TenantMgmtApi_ServiceDesc, srv)
}

func _TenantMgmtApi_GetTenantLevelKycStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMgmtApiServer).GetTenantLevelKycStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.TenantMgmtApi/GetTenantLevelKycStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMgmtApiServer).GetTenantLevelKycStatus(ctx, req.(*GenericStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMgmtApi_GetTenantUserLevelKycStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantUserLevelKycStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMgmtApiServer).GetTenantUserLevelKycStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.TenantMgmtApi/GetTenantUserLevelKycStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMgmtApiServer).GetTenantUserLevelKycStatus(ctx, req.(*TenantUserLevelKycStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMgmtApi_GetPaymentMethodConfigurationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMgmtApiServer).GetPaymentMethodConfigurationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.TenantMgmtApi/GetPaymentMethodConfigurationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMgmtApiServer).GetPaymentMethodConfigurationStatus(ctx, req.(*GenericStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantMgmtApi_GetTenantType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantMgmtApiServer).GetTenantType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.TenantMgmtApi/GetTenantType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantMgmtApiServer).GetTenantType(ctx, req.(*GenericStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantMgmtApi_ServiceDesc is the grpc.ServiceDesc for TenantMgmtApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantMgmtApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.TenantMgmtApi",
	HandlerType: (*TenantMgmtApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTenantLevelKycStatus",
			Handler:    _TenantMgmtApi_GetTenantLevelKycStatus_Handler,
		},
		{
			MethodName: "GetTenantUserLevelKycStatus",
			Handler:    _TenantMgmtApi_GetTenantUserLevelKycStatus_Handler,
		},
		{
			MethodName: "GetPaymentMethodConfigurationStatus",
			Handler:    _TenantMgmtApi_GetPaymentMethodConfigurationStatus_Handler,
		},
		{
			MethodName: "GetTenantType",
			Handler:    _TenantMgmtApi_GetTenantType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant-mgmt.proto",
}
