name: Build Docker images with latest tag on every merge to main branch
on:
  push:
    branches: [ main ]
jobs:
  auth-build-latest:
    runs-on: newgroup
    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PWD: ${{secrets.DOCKERHUB_PUSH_TOKEN}}
      run: sudo docker login -u $DOCKER_USER -p $DOCKER_PWD
    - name: Set up Go Environment
      uses: actions/setup-go@v2
      with:
        go-version: "1.22.x"
    - name: Build docker image
      env:
        GIT_TOKEN: ${{secrets.AUTH_SECRET_01}}
      run: |
        git config --global url."https://${GIT_TOKEN}:x-oauth-basic@github.com/coredgeio".insteadOf "https://github.com/coredgeio"
        go env -w GOPRIVATE=github.com/coredgeio/*
        make -j2
    - name: Push the docker image
      run: make push-images
    - name: cleanup the docker
      run: sudo docker logout && sudo docker system prune -a -f
