name: Validate build for pull request
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  auth-build-pull-request:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go Environment
      uses: actions/setup-go@v2
      with:
        go-version: "1.22.x"
    - name: Build docker image
      env:
        GIT_TOKEN: ${{secrets.AUTH_SECRET_01}}
      run: |
        git config --global url."https://${GIT_TOKEN}:x-oauth-basic@github.com/coredgeio".insteadOf "https://github.com/coredgeio"
        go env -w GOPRIVATE=github.com/coredgeio/*
        make -j2
    - name: cleanup the docker
      run: sudo docker system prune -a -f
  golangci:
    name: golangci-lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.22.x"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
